### ISSUE TITLE
confusing sentence

### ISSUE THREAD

**Issue by jarantfos** [EditLLC/client-knot-away#26] opened 2015-12-30 23:28 UTC
" I transferred to Massage Envy in Clovis, which I been working since 2012. "

Can you please ask the client for clarification on this sentence or tell me what you think it should say? Thanks

**Comment by jarantfos** [comment] 2015-12-30 23:32
And this one:

" I can help you feel like the best you I can possible do. "

**Comment by rodneystrong** [comment] 2016-01-05 22:33
Hahaha, i can understand the confusion. Thanks for finding these. I'll paste my fixes here.

**Comment by rodneystrong** [comment] 2016-01-05 22:44
The first one is a usage error and borderline slang. The author is implying historical significance of her work. In other words, just stating her past work history. Keyword here is "past", so we need to use the past perfect tense here in addition to using the word "since" as a conjunction. 
I changed this sentence to: I transferred to Massage Envy in Clovis, where I have worked since 2012.

The second one is another usage error but fixing it requires a bit of mimicking the author's tone. The issue is simply having too many pronouns.
I changed this sentence to: I can help you feel like the best you can possibly be.

Fixing both of these errors required a bit of intuition and prediction on what the author was implying. Remind me to do an exercise with you on this so you can start developing that intuition.

**Closed by rodneystrong** 2016-01-05 22:44 UTC
Labels: help wanted, task
